### ISSUE TITLE
v0.392 depends on non-existent Data::Clean 0.505

### ISSUE THREAD

**Issue by cxw42** [perlancar/perl-Data-Clean-JSON#1]
Trying to install App::xsum on another system today, I received a failure report from cpm.  I think it is because this module now requires Data::Clean 0.505, but I can't find any Data::Clean newer than 0.502.  Would you be willing to look into this?  Thank you!

**Edit** I manually installed Data::Clean::JSON 0.391 from the tarball and then was able to install xsum successfully using cpm.

**Comment by perlancar** [comment]
Sorry for the late response, didn't see the notification.

I believe this issue has been self-resolved.
